default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: <%= "check_product_development" %>

test:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME']}_test" %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
